brand_name:
  default: 'Financial Peace'
website_url:
  default: 'www.finacialpeace.com'
logo_url:
  default: ''
mobile_logo_url:
  default: ''
links:
  type: list
  default: ''
icons:
  type: list
  default: ''
daily_check_in:
  type: string
  default: ''
  description: "Enter full url for the Daily Check-in link on Homepage."
introduce_yourself:
  type: string
  default: ''
  description: "Enter full url for Introduce Yourself link on Homepage."
